In [4]:
import torch

In [5]:
torch.empty(3,2)

tensor([[1.6764e+22, 6.5925e-10],
        [2.6659e-09, 2.6332e+20],
        [8.1923e-10, 2.1512e+23]])

In [6]:
torch.rand(3)

tensor([0.7760, 0.3681, 0.3723])

In [7]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [8]:
torch.ones(2,2).dtype

torch.float32

In [9]:
x = torch.ones(2,2, dtype=torch.float16)

In [10]:
x.size()

torch.Size([2, 2])

In [11]:
torch.tensor([2.4, 5.4])

tensor([2.4000, 5.4000])

## Reshaping

In [12]:
x = torch.rand(4,4)

In [13]:
print(x)

tensor([[0.7518, 0.6449, 0.4732, 0.0467],
        [0.6640, 0.4396, 0.6777, 0.0513],
        [0.1362, 0.7639, 0.1150, 0.2579],
        [0.3698, 0.2554, 0.3097, 0.6514]])


In [14]:
x.view(16)

tensor([0.7518, 0.6449, 0.4732, 0.0467, 0.6640, 0.4396, 0.6777, 0.0513, 0.1362,
        0.7639, 0.1150, 0.2579, 0.3698, 0.2554, 0.3097, 0.6514])

In [15]:
x.view(-1,8)

tensor([[0.7518, 0.6449, 0.4732, 0.0467, 0.6640, 0.4396, 0.6777, 0.0513],
        [0.1362, 0.7639, 0.1150, 0.2579, 0.3698, 0.2554, 0.3097, 0.6514]])

## Numpy and Pytorch

In [16]:
import numpy as np

In [17]:
a = torch.ones(5)

print(a)

b = a.numpy()

print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


In [19]:
a = np.ones(5)

print(a)

b = torch.from_numpy(a)

print(type(b))
print(b)
print(a+1)
print(b)    #Tensor does a deep copy when running on cpu  but not on GPU

[1. 1. 1. 1. 1.]
<class 'torch.Tensor'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## In PyTorch, you can create a deep copy of a tensor using the .clone() method or the torch.clone() function. Both methods /create a new tensor that is a deep copy of the original tensor, meaning they have separate memory locations and changes made to one tensor will not affect the other. Here's how you can use them:

## Using .clone() method:

In [1]:
import torch

# Create the original tensor
original_tensor = torch.tensor([1, 2, 3])

# Create a deep copy of the tensor using .clone()
deep_copied_tensor = original_tensor.clone()

# Modify the deep copied tensor
deep_copied_tensor[0] = 100

# The original tensor remains unchanged
print(original_tensor)         # Output: tensor([1, 2, 3])
print(deep_copied_tensor)      # Output: tensor([100, 2, 3])


tensor([1, 2, 3])
tensor([100,   2,   3])


## Using torch.clone() function:

In [2]:
import torch

# Create the original tensor
original_tensor = torch.tensor([1, 2, 3])

# Create a deep copy of the tensor using torch.clone()
deep_copied_tensor = torch.clone(original_tensor)

# Modify the deep copied tensor
deep_copied_tensor[0] = 100

# The original tensor remains unchanged
print(original_tensor)         # Output: tensor([1, 2, 3])
print(deep_copied_tensor)      # Output: tensor([100, 2, 3])


tensor([1, 2, 3])
tensor([100,   2,   3])


## Cuda

In [23]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu")      
    print(z)
                   
                   
                   
                   
                   

## Single Value

In [25]:
x = torch.tensor(2)

In [26]:
x.item()

2