In [2]:
import torch

In [3]:
x =  torch.randn(3, requires_grad = True)
print(x)   

tensor([0.2642, 1.7199, 0.2944], requires_grad=True)


In [5]:
y  = x + 2 
print(y)   

tensor([2.2642, 3.7199, 2.2944], grad_fn=<AddBackward0>)


z=y*y*2
z=z.mean()
print(z)

In [7]:
z.backward() #dy/dx
print(x.grad)

tensor([3.0189, 4.9599, 3.0591])


## How to exclude a tensor from gradiant calculations

In [ ]:
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

## Resetting the gradients to Zero on each Training Epoch 

In [11]:
import torch

weights = torch.ones(4, requires_grad = True)
for epoch in range(3):
    
    model_output = (weights * 3).sum()
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


## Resetting the gradients to Zero on each Training Epoch example 2

In [2]:
# import torch

# weights = torch.ones(4, requires_grad = True)
# optimizer = torch.optim.SGD(weights, lr=0.01)
# optimizer.step()
# optimizer.zero_grad()